[project]
name = "dacn-nhom14"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "torchvision",
    "numpy",
    "uvicorn>=0.35.0",
    "pandas>=2.3.3",
    "opencv-python>=4.11.0.86",
]

